import 'package:MovieBookingApplication/data/vo/date_vo.dart';

List<DateVO> dateData = [
  DateVO(id: 1, day: "Sun", date: "1"),
  DateVO(id: 2, day: "Mon", date: "2"),
  DateVO(id: 3, day: "Tues", date: "3"),
  DateVO(id: 4, day: "Wed", date: "4"),
  DateVO(id: 5, day: "Thurs", date: "5"),
  DateVO(id: 6, day: "Fri", date: "6"),
  DateVO(id: 7, day: "Sat", date: "7"),
  DateVO(id: 8, day: "Sun", date: "8"),
  DateVO(id: 9, day: "Mon", date: "9"),
  DateVO(id: 10, day: "Tues", date: "10"),
  DateVO(id: 11, day: "Wed", date: "11"),
  DateVO(id: 12, day: "Thurs", date: "12"),
  DateVO(id: 13, day: "Fri", date: "13"),
  DateVO(id: 14, day: "Sat", date: "14"),
  DateVO(id: 15, day: "Sun", date: "15"),
  DateVO(id: 16, day: "Mon", date: "16"),
  DateVO(id: 17, day: "Tues", date: "17"),
  DateVO(id: 18, day: "Wed", date: "18"),
  DateVO(id: 19, day: "Thurs", date: "19"),
  DateVO(id: 20, day: "Fri", date: "20"),
  DateVO(id: 21, day: "Sat", date: "21"),
  DateVO(id: 22, day: "Sun", date: "22"),
  DateVO(id: 23, day: "Mon", date: "23"),
  DateVO(id: 24, day: "Tues", date: "24"),
  DateVO(id: 25, day: "Wed", date: "25"),
  DateVO(id: 26, day: "Thurs", date: "26"),
  DateVO(id: 27, day: "Fri", date: "27"),
  DateVO(id: 28, day: "Sat", date: "28"),
  DateVO(id: 29, day: "Sun", date: "29"),
  DateVO(id: 30, day: "Mon", date: "30"),
];
