//Hive Types
const int HIVE_TYPE_ID_USER_DATA_VO = 1;
const int HIVE_TYPE_ID_lOG_IN_DATA_RESPONSE_DATA = 2;
const int HIVE_TYPE_ID_CARD_VO = 3;
const int HIVE_TYPE_ID_MOVIE_VO = 4;
const int HIVE_TYPE_ID_MOVIE_DETAIL_VO = 5;
const int HIVE_TYPE_ID_CAST_VO = 6;
const int HIVE_TYPE_ID_CINEMA_VO = 7;
const int HIVE_TYPE_ID_TIME_SLOT_VO = 8;
const int HIVE_TYPE_ID_SNACK_VO = 9;
const int HIVE_TYPE_PROFILE_VO = 10;
// const int HIVE_TYPE_ID_BASE_ACTOR_VO = 2;
// const int HIVE_TYPE_ID_COLLECTION_VO = 3;
// const int HIVE_TYPE_ID_CREDIT_VO = 4;
// const int HIVE_TYPE_ID_DATE_VO = 5;
// const int HIVE_TYPE_ID_GENRE_VO = 6;
// const int HIVE_TYPE_ID_MOVIE_VO = 7;
// const int HIVE_TYPE_ID_PRODUCTION_COMPANIES_VO = 8;
// const int HIVE_TYPE_ID_PRODUCTION_COUNTRIES_VO = 9;
// const int HIVE_TYPE_ID_SPOKEN_LANGUAGES_VO = 10;

//Box Names
const String BOX_NAME_LOGIN_DATA_RESPONSE_VO = "BOX_NAME_LOGIN_DATA_VO";
const String BOX_NAME_ACTOR_VO = "BOX_NAME_ACTOR_VO";
const String BOX_NAME_BASE_ACTOR_VO = "BOX_NAME_BASE_ACTOR_VO";
const String BOX_NAME_COLLECTION_VO = "BOX_NAME_COLLECTION_VO";
const String BOX_NAME_CREDIT_VO = "BOX_NAME_CREDIT_VO";
const String BOX_NAME_DATE_VO = "BOX_NAME_DATE_VO";
const String BOX_NAME_GENRE_VO = "BOX_NAME_GENRE_VO";
const String BOX_NAME_MOVIE_VO = "BOX_NAME_MOVIE_VO";
const String BOX_NAME_MOVIE_DETAIL_VO = "BOX_NAME_MOVIE_DETAIL_VO";
const String BOX_NAME_PRODUCTION_COMPANIES_VO =
    "BOX_NAME_PRODUCTION_COMPANIES_VO";
const String BOX_NAME_PRODUCTION_COUNTRIES_VO =
    "BOX_NAME_PRODUCTION_COUNTRIES_VO";
const String BOX_NAME_SPOKEN_LANGUAGES_VO = "BOX_NAME_SPOKEN_LANGUAGES_VO";
const String BOX_NAME_CAST_VO = "BOX_NAME_CAST_VO";
const String BOX_NAME_CINEMA_VO = "BOX_NAME_CINEMA_VO";
const String BOX_NAME_TIME_SLOT_VO = "BOX_NAME_TIME_SLOT_VO";
const String BOX_NAME_SNACK_VO = "BOX_NAME_SNACK_VO";
const String BOX_NAME_PROFILE_VO = "BOX_NAME_PROFILE_VO";
